GET http://localhost/bank-accounts

###
GET http://localhost/bank-accounts/e91c0cf4-c591-467b-8c0a-76ccb33e5d9b

###
POST http://localhost/bank-accounts
Content-Type: application/json

{
    "account_number": "3333-33"
}

###
PATCH http://localhost/bank-accounts/123
Content-Type: application/json

{
    "account_number": "4444-44"
}

###
DELETE http://localhost/bank-accounts/123

###
POST http://localhost/bank-accounts/tranfer
Content-Type: application/json

{
    "from": "1111-11",
    "to": "3333-33",
    "amount": 100
}

###
POST http://localhost/anexos/file
